package com.eykon.memory.assistant

import android.content.Context
import com.eykon.memory.data.MemoryRecord
import com.google.ai.edge.litertlm.Backend
import com.google.ai.edge.litertlm.Content
import com.google.ai.edge.litertlm.Engine
import com.google.ai.edge.litertlm.EngineConfig
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/**
 * On-device LLM generation engine wrapper for Gemma 4 LiteRT-LM.
 */
class LiteRTGenerator(
    private val context: Context,
    val params: GenerationParams = GenerationParams()
) {

    @Volatile
    private var engineInstance: Engine? = null
    private var loadedModelPath: String? = null

    private fun getOrInitEngine(modelPath: String): Engine {
        val currentEngine = engineInstance
        if (currentEngine != null && loadedModelPath == modelPath && currentEngine.isInitialized()) {
            return currentEngine
        }

        synchronized(this) {
            if (engineInstance != null && loadedModelPath == modelPath && engineInstance!!.isInitialized()) {
                return engineInstance!!
            }

            engineInstance?.close()

            // Force CPU backend to avoid OpenCL discovery crash poisoning the C++ engine
            val config = EngineConfig(
                modelPath = modelPath,
                backend = Backend.CPU()
            )
            val newEngine = Engine(config)
            newEngine.initialize()
            
            engineInstance = newEngine
            loadedModelPath = modelPath
            return newEngine
        }
    }

    suspend fun generateAnswer(
        question: String,
        contextMemories: List<MemoryRecord>
    ): GenerationResult = withContext(Dispatchers.Default) {
        val startTime = System.currentTimeMillis()
        val prompt = PromptBuilder.buildRagPrompt(question, contextMemories)
        val status = ModelManager.getModelStatus(context)

        if (!status.isAvailable) {
            val latency = System.currentTimeMillis() - startTime
            return@withContext GenerationResult(
                answer = "Gemma 4 model file (${ModelManager.MODEL_FILENAME}) not found at:\n${status.filePath}\n\nTo sideload the 2.4 GB model to your device, run:\n${status.adbPushCommand}",
                latencyMs = latency,
                isModelFound = false,
                fullPrompt = prompt
            )
        }

        try {
            val engine = getOrInitEngine(status.filePath)
            var conversation: com.google.ai.edge.litertlm.Conversation? = null
            val rawOutput = try {
                kotlin.coroutines.suspendCoroutine<String> { continuation ->
                    val sb = java.lang.StringBuilder()
                    conversation = engine.createConversation()
                    
                    conversation?.sendMessageAsync(prompt, object : com.google.ai.edge.litertlm.MessageCallback {
                        override fun onMessage(message: com.google.ai.edge.litertlm.Message) {
                            for (content in message.contents.contents) {
                                if (content is Content.Text) {
                                    sb.append(content.text)
                                }
                            }
                        }

                        override fun onDone() {
                            continuation.resumeWith(Result.success(sb.toString()))
                        }

                        override fun onError(t: Throwable) {
                            continuation.resumeWith(Result.failure(t))
                        }
                    })
                }
            } finally {
                conversation?.close()
            }

            val cleanedOutput = cleanAnswer(rawOutput.ifBlank { "No output generated by model." })
            val latency = System.currentTimeMillis() - startTime

            GenerationResult(
                answer = cleanedOutput,
                latencyMs = latency,
                isModelFound = true,
                fullPrompt = prompt
            )
        } catch (e: Throwable) {
            val latency = System.currentTimeMillis() - startTime
            GenerationResult(
                answer = "Inference error: ${e.localizedMessage ?: e.javaClass.simpleName}",
                latencyMs = latency,
                isModelFound = true,
                fullPrompt = prompt,
                error = e.localizedMessage ?: e.javaClass.simpleName
            )
        }
    }

    companion object {
        fun cleanAnswer(rawText: String): String {
            var text = rawText.trim()
            if (text.startsWith("Answer:", ignoreCase = true)) {
                text = text.substring(7).trim()
            }
            return text
        }
    }
}

data class GenerationResult(
    val answer: String,
    val latencyMs: Long,
    val isModelFound: Boolean,
    val fullPrompt: String,
    val error: String? = null
)
